# Matrix


In [25]:
# Matrix multplication 

import numpy as np
r=int(input())
c=int(input())
value1=list(map(int,input().split()))
value2=list(map(int,input().split()))
matrix1=np.array(value1).reshape(r,c)
matrix2=np.array(value2).reshape(r,c)
mat=np.zeros((r,c))

for i in range(len(matrix1)):
    for j in range(len(matrix2)):
        for k in range(len(matrix2)):
            mat[i][j]+=matrix1[i][k]*matrix2[k][j]
            
print(mat)

2
2
1 2 3 4
2 3 4 5
[[10. 13.]
 [22. 29.]]


In [28]:
# Matrix addition

import numpy as np
r=int(input())
c=int(input())
value1=list(map(int,input().split()))
value2=list(map(int,input().split()))
matrix1=np.array(value1).reshape(r,c)
matrix2=np.array(value2).reshape(r,c)
mat3=matrix1+matrix2;print(mat3)

2
2
1 2 3 4 
2 2 3 4
[[3 4]
 [6 8]]


In [29]:
# Matrix substarction 

import numpy as np
r=int(input());c=int(input())
val1=list(map(int,input().split()));val2=list(map(int,input().split()))
m=np.array(val1).reshape(r,c);n=np.array(val2).reshape(r,c)
result=m-n
print(result)

2
2
1 2 3 4
2 3 4 5
[[-1 -1]
 [-1 -1]]


In [31]:
# 90degree left rotation of Matrix

r=int(input());c=int(input())
val=list(map(int,input().split()))
matrix=np.array(val).reshape(r,c)
temp=np.array(val).reshape(r,c)
for i in range(r):
    for j in range(c):
        matrix[i][j]=temp[j][r-i-1]
             
print(matrix)

3
3
2 3 4 2 3 5 6 7 8
[[4 5 8]
 [3 3 7]
 [2 2 6]]


In [34]:
# Transpose of Matrix

r=int(input());c=int(input())
val=list(map(int,input().split()))
matrix=np.array(val).reshape(r,c)
tran=np.array(val).reshape(c,r)
for i in range(c):
    for j in range(r):
        tran[i][j]=matrix[j][i]
print(matrix)
print(tran)


2
2
1 2 3 4
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [55]:
# Search Element in Row-wise and Column-wise Sorted Matrix

def search(mat,x):
    
    n=len(mat)
    i=0;j=n-1
    while(i<n and j>=0):

        if mat[i][j]==x:
            print(i,j)
            break
        elif mat[i][j]>x:
            j-=1
        else:
            i+=1
            
mat=[[1,2,3],
    [4,5,6],
    [7,8,9]]
search(mat,3)


0 2


In [22]:
# Spiral Traversal of Matrix

import numpy as np

def spiralmat(mat,n):
    top=0;down=n-1;left=0;right=n-1
    di=0
    while top<=down and left<=right:
        if di==0:
            for i in range(left,right+1):
                print(mat[top][i])
            top+=1
        elif di==1:
            
            for i in range(top,down+1):
            
                print(mat[i][right])
            right-=1
        elif di==2:
            for i in range(right,left-1,-1):
                
                print(mat[down][i])
            down-=1
        elif di==3:
            for i in range(down,top-1,-1):
                print(mat[i][left])
            left+=1
        di=(di+1)%4
    

n=int(input())
val=list(map(int,input().split()))
mat=np.array(val).reshape(n,n)
spiralmat(mat,n)

4
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
1
2
3
4
8
12
16
15
14
13
9
5
6
7
11
10
