# Knapsack

In [32]:
# 0-1 knapsack

def knapsack(wt,val,weight,n):
    if n==0 or weight==0:
        return 0
    if wt[n-1]<=weight:
        return max(val[n-1]+knapsack(wt,val,weight-wt[n-1],n-1),knapsack(wt,val,weight,n-1))
    elif wt[n-1]>weight:
        return knapsack(wt,val,weight,n-1)
wt=[1,3,4,5]
val=[1,4,5,7] 
weight=7
n=len(wt)
knapsack(wt,val,weight,n)

9

In [48]:
# 0-1 knapsack (memoziation)

import numpy as np
r=n+1
c=weight+1
val=[-1]*r*c
matrix=np.array(val).reshape(r,c)


def knapsack(wt,val,weight,n):
    if n==0 or weight==0:
        return 0
    if matrix[n][weight]!=-1: 
        
        return matrix[n][weight]
    
    if wt[n-1]<=weight:
        matrix[n][weight]=max(val[n-1]+knapsack(wt,val,weight-wt[n-1],n-1),knapsack(wt,val,weight,n-1))
        return matrix[n][weight]
        
    elif wt[n-1]>weight:
        matrix[n][weight]=knapsack(wt,val,weight,n-1)
        return matrix[n][weight]
    
    
wt=[10, 20, 30]
val=[60, 100, 120]
weight=50
n=len(wt)
knapsack(wt,val,weight,n)

220

In [81]:
# 0-1 knapsack (top-down)

import numpy as np

wt=[1,3,4,5]
val=[1,4,5,7]
weight=7
n=len(wt)

r=n+1
c=weight+1
v=[-1]*r*c
mat=np.array(v).reshape(r,c) 

for i in range(r):
    for j in range(c):
        if i==0 or j==0:
            mat[i][j]=0
            
    
for i in range(1,r):
    for j in range(1,c):
        
        if wt[i-1]<=j:
            mat[i][j]=max(val[i-1]+mat[i-1][j-wt[i-1]],mat[i-1][j])
            
        else:
            mat[i][j]=mat[i-1][j]

print(mat)
print(mat[n][weight])



[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1]
 [0 1 1 4 5 5 5 5]
 [0 1 1 4 5 6 6 9]
 [0 1 1 4 5 7 8 9]]
9


In [7]:
# Subset sum problem:
arr=[3, 34, 4, 12, 5, 2]
su=10

import numpy as np
r=len(arr)+1
c=su+1
v=[0]*(r)*(c)
mat=np.array(v).reshape(r,c)

for i in range(r):
    for j in range(c):
        if i==0:
            mat[i][j]=False
        if j==0:
            mat[i][j]=True
            
for i in range(1,r):
    for j in range(1,c):
        if arr[i-1]<=j:
            mat[i][j]=(mat[i-1][j-arr[i-1]]) or (mat[i-1][j])
        else:
            mat[i][j]=mat[i-1][j]

print(mat)

print(bool(mat[r-1][c-1]))

[[1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 0 1 0 0 0]
 [1 0 0 1 1 0 0 1 0 0 0]
 [1 0 0 1 1 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1 1]]
True


In [9]:
# Equal sum partition problem 
arr=[1,5,5,11]

def subset_sum(arr,su):
    import numpy as np
    r=len(arr)+1
    c=su+1
    v=[0]*(r)*(c)
    mat=np.array(v).reshape(r,c)

    for i in range(r):
        for j in range(c):
            if i==0:
                mat[i][j]=False
            if j==0:
                mat[i][j]=True

    for i in range(1,r):
        for j in range(1,c):
            if arr[i-1]<=j:
                mat[i][j]=(mat[i-1][j-arr[i-1]]) or (mat[i-1][j])
            else:
                mat[i][j]=mat[i-1][j]
    return bool(mat[r-1][c-1])

def equal(arr):
    su=sum(arr)
    if su%2!=0:
        return False
    else:
        return subset_sum(arr,su//2)

equal(arr)

True

In [5]:
# Count sub_set sum problem

arr=[2,3,5,6,8,10]
su=10

import numpy as np
r=len(arr)+1
c=su+1
v=[0]*(r)*(c)
mat=np.array(v).reshape(r,c)

for i in range(r):
    for j in range(c):
        if i==0:
            mat[i][j]=False
        if j==0:
            mat[i][j]=True
            
for i in range(1,r):
    for j in range(1,c):
        if arr[i-1]<=j:
            mat[i][j]=(mat[i-1][j-arr[i-1]]) + (mat[i-1][j])
        else:
            mat[i][j]=mat[i-1][j]

print(mat)
print(mat[r-1][c-1])

[[1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 0 0 0]
 [1 0 1 1 0 2 0 1 1 0 1]
 [1 0 1 1 0 2 1 1 2 1 1]
 [1 0 1 1 0 2 1 1 3 1 2]
 [1 0 1 1 0 2 1 1 3 1 3]]
3


In [46]:
# Minimum subset sum diff

arr=[3, 1, 4, 2, 2, 1]

import numpy as np
r=len(arr)+1
su=sum(arr)
c=su+1
v=[0]*(r)*(c)
mat=np.array(v).reshape(r,c)

for i in range(r):
    for j in range(c):
        if i==0:
            mat[i][j]=False
        if j==0:
            mat[i][j]=True

for i in range(1,r):
    for j in range(1,c):
        if arr[i-1]<=j:
            mat[i][j]=(mat[i-1][j-arr[i-1]]) or (mat[i-1][j])         # this para code is from subset sum as it is same.
        else:
            mat[i][j]=mat[i-1][j]

            
            
arr1=mat[r-1]
arr3=[]
for i in range(len(arr1)//2):
    if arr1[i]==1:
        arr3.append(i)

        
mn=float('inf')
for k in range(len(arr3)):
    mn=min(mn,su-(2*arr3[k]))

print(mn)


1


In [63]:
# COunt the number of subset with given diff

arr=[1,1,2,3]
diff=1

def count_subset_diff(arr,diff):
    su=sum(arr)
    sum_s1=(diff+su)//2
    return count_subset_sum(arr,sum_s1)

def count_subset_sum(arr,sum_s1):
    import numpy as np
    r=len(arr)+1
    c=sum_s1+1
    v=[0]*(r)*(c)
    mat=np.array(v).reshape(r,c)
    
    for i in range(r):
        for j in range(c):
            if i==0:
                mat[i][j]=False
            if j==0:
                mat[i][j]=True
    
    for i in range(1,r):
        for j in range(1,c):
            if(arr[i-1]<=j):
                mat[i][j]=mat[i-1][j-arr[i-1]] + mat[i-1][j]
            else:
                mat[i][j]=mat[i-1][j]

    return mat[r-1][c-1]


count_subset_diff(arr,diff)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 2 1 0 0]
 [1 2 2 2 1]
 [1 2 2 3 3]]


3

In [69]:
# Unbounded knapsack
import numpy as np

wt=[1,3,4,5]
val=[1,4,5,7]
weight=7
n=len(wt)

r=n+1
c=weight+1
v=[-1]*r*c
mat=np.array(v).reshape(r,c) 

for i in range(r):
    for j in range(c):
        if i==0 or j==0:
            mat[i][j]=0
            
    
for i in range(1,r):
    for j in range(1,c):
        
        if wt[i-1]<=j:
            mat[i][j]=max(val[i-1]+mat[i][j-wt[i-1]],mat[i-1][j])
            
        else:
            mat[i][j]=mat[i-1][j]

print(mat[n][weight])


9


In [72]:
# Rod cutting problem
import numpy as np

length=[1,2,3,4,5,6,7,8]
price=[1,5,8,9,10,17,17,20]
N=8

r=len(length)+1
c=N+1
v=[-1]*r*c
mat=np.array(v).reshape(r,c)

for i in range(r):
    for j in range(c):
        if i==0 or j==0:
            mat[i][j]=0

for i in range(1,r):
    for j in range(1,c):
        if(length[i-1]<=j):
            mat[i][j]=max(price[i-1]+mat[i][j-length[i-1]],mat[i-1][j])
        else:
            mat[i][j]=mat[i-1][j]

print(mat[r-1][c-1])

22


In [21]:
# Coin Change I 

coin=[1,2,3]
su=4

def coin_change(coin,su):
    import numpy as np
    r=len(coin)+1
    c=su+1
    v=[-1]*r*c
    mat=np.array(v).reshape(r,c)
    
    for i in range(r):
        for j in range(c):
            if(i==0):
                mat[i][j]=0
            if j==0:
                mat[i][j]=1
    
    for i in range(1,r):
        for j in range(1,c):
            if(coin[i-1]<=j):
                mat[i][j]=mat[i-1][j]+mat[i][j-coin[i-1]]
            else:
                mat[i][j]=mat[i-1][j]
    return mat[r-1][c-1]
    
    
coin_change(coin,su)

4

In [13]:
# Coin Change II

import numpy as np
arr=[1,2,3]
su=3

def coin_change2(arr,su):
    r=len(arr)+1
    c=su+1
    v=[-1.0]*r*c
    mat=np.array(v).reshape(r,c)
    
    for i in range(r):
        for j in range(c):
            if i==0:
                mat[i][j]=float('inf')-1
            if i!=0 and j==0:
                mat[i][j]=0
            if i==1 and j%arr[0]==0:
                mat[i][j]=j/arr[0]
            elif i==1 and j%arr[0]!=0:
                mat[i][j]=float('inf')-1
    
    for i in range(2,r):
        for j in range(1,c):
            if(arr[i-1]<=j):
                mat[i][j]=min(1+mat[i][j-arr[i-1]],mat[i-1][j])
            else:
                mat[i][j]=mat[i-1][j]
                
    return int(mat[r-1][c-1])

coin_change2(arr,su)


1

# Longest Common Sub-Sequence

In [14]:
# Recursive approach of LCS

x="abcdgh"
y="abedfhr"
n=len(x)
m=len(y)

def LCS(x,y,n,m):
    if(n==0 or m==0):
        return 0
    if(x[n-1]==y[m-1]):
        return 1+LCS(x,y,n-1,m-1)
    else:
        return max(LCS(x,y,n,m-1),LCS(x,y,n-1,m))
    
LCS(x,y,n,m)

4

In [35]:
# Buttom-up memoziation of LCS (DP)

import numpy as np
x="abcdgh"
y="abedfhr"
m=len(x)
n=len(y)
v=[-1]*(n+1)*(m+1)

mat=np.array(v).reshape(m+1,n+1)

def LCS_DP(x,y,m,n):
    if(m==0 or n==0):
        return 0
    if(mat[m][n]!=-1):
        return mat[m][n]
    
    if(x[m-1]==y[n-1]):
        mat[m][n]=1+LCS_DP(x,y,m-1,n-1)
        return mat[m][n]
    else:
        mat[m][n]=max(LCS_DP(x,y,m,n-1),
                            LCS_DP(x,y,m-1,n))
        return mat[m][n]
    
LCS_DP(x,y,m,n)

4

In [26]:
# Top-Down DP of LCS

import numpy as np
x="abcdgh"
y="abedfhr"

m=len(x)
n=len(y)
v=[-1]*(n+1)*(m+1)
# global mat

def LCS(x,y,m,n):
    mat=np.array(v).reshape(m+1,n+1)
    for i in range(m+1):
        for j in range(n+1):
            if i==0 or j==0:
                mat[i][j]=0
    for i in range(1,m+1):
        for j in range(1,n+1):
            if(x[i-1]==y[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i-1][j],mat[i][j-1])
    print(mat)
    return mat[m][n]

LCS(x,y,m,n)

[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1]
 [0 1 2 2 2 2 2 2]
 [0 1 2 2 2 2 2 2]
 [0 1 2 2 3 3 3 3]
 [0 1 2 2 3 3 3 3]
 [0 1 2 2 3 3 4 4]]


4

In [4]:
# Longest Common subString 
import numpy as np
x="eat"
y="ate"

m=len(x)
n=len(y)
v=[-1]*(n+1)*(m+1)
# global mat

def LCS(x,y,m,n):
    mat=np.array(v).reshape(m+1,n+1)
    for i in range(m+1):
        for j in range(n+1):
            if i==0 or j==0:
                mat[i][j]=0
    for i in range(1,m+1):
        for j in range(1,n+1):
            if(x[i-1]==y[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=0
    print(mat)
    return np.max(mat)

LCS(x,y,m,n)

[[0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 2 0]]


2

In [41]:
# Print Longest Common subsequence
import numpy as np

x="abcdgh"
y="abedfhr"
m=len(x)
n=len(y)
v=[-1]*(n+1)*(m+1)

mat=np.array(v).reshape(m+1,n+1)

def LCS(x,y,m,n):
    for i in range(m+1):
        for j in range(n+1):
            if i==0 or j==0:
                mat[i][j]=0
    
    for i in range(1,m+1):
        for j in range(1,n+1):
            if(x[i-1]==y[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i][j-1],
                             mat[i-1][j])
    return mat

t=LCS(x,y,m,n)
i=m;j=n
ans=""
while(i>0 and j>0):
    if(x[i-1]==y[j-1]):
        ans+=x[i-1]
        i-=1
        j-=1
    else:
        if t[i][j-1]>t[i-1][j]:
            j-=1
        else:
            i-=1

print(ans[::-1])

abdh


In [45]:
# Shorted Common SuperSequence 

import numpy as np
a="AGGTAB"
b="GXTXAYB"
m=len(a)
n=len(b)

v=[-1]*(m+1)*(n+1)
mat=np.array(v).reshape(m+1,n+1)

def LCS(a,b,m,n):
    for i in range(m+1):
        for j in range(n+1):
            if(i==0 or j==0):
                mat[i][j]=0
                
    for i in range(1,m+1):
        for j in range(1,n+1):
            if(a[i-1]==b[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i-1][j],
                             mat[i][j-1])
    return mat[m][n]

ans=(m+n)-LCS(a,b,m,n)
print(ans)

9


In [46]:
# Minimun number of insertion and delection to convert String a to String b

import numpy as np
a="heap"
b="pea"
m=len(a)
n=len(b)
v=[-1]*(m+1)*(n+1)

mat=np.array(v).reshape(m+1,n+1)
def LCS(a,b,m,n):
    for i in range(m+1):
        for j in range(n+1):
            if i==0 or j==0:
                mat[i][j]=0
    
    for i in range(1,m+1):
        for j in range(1,n+1):
            if(a[i-1]==b[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i-1][j],
                             mat[i][j-1])
    return mat[m][n]

print("Min Insertion: ",len(b)-LCS(a,b,m,n))
print("Min Delection: ",len(a)-LCS(a,b,m,n))

Min Insertion:  1
Min Delection:  2


In [54]:
# Longest Palindromic SubSequence

import numpy as np
a='agbcba'

def LPS(a):
    return LCS(a,a[::-1],len(a),len(a))

def LCS(a,b,m,n):
    
    v=[-1]*(m+1)*(n+1)
    mat=np.array(v).reshape(m+1,n+1)
    for i in range(m+1):
        for j in range(n+1):
            if(i==0 or j==0):
                mat[i][j]=0
                
    for i in range(1,m+1):
        for j in range(1,n+1):
            if(a[i-1]==b[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i-1][j],
                             mat[i][j-1])
    return mat[m][n]

LPS(a)

5

In [57]:
# Minimum no. of delection in a String to make it a palindrome

a="agbcba"
print(len(a)-LPS(a))


1


In [60]:
# Print SCS (Shortest Common subSequence)
import numpy as np

a="acbcf"
b="abcdaf"
m=len(a)
n=len(b)

v=[-1]*(m+1)*(n+1)
mat=np.array(v).reshape(m+1,n+1)

def SCS(a,b,m,n):
    for i in range(m+1):
        for j in range(n+1):
            if i==0 or j==0:
                mat[i][j]=0
                
    for i in range(1,m+1):
        for j in range(1,n+1):
            if(a[i-1]==b[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i-1][j],
                             mat[i][j-1])
    
    i=m;j=n;ans=""
    while i>0 and j>0:
        if(a[i-1]==b[j-1]):
            ans+=a[i-1]
            i-=1
            j-=1
        else:
            if(mat[i-1][j]>mat[i][j-1]):
                ans+=a[i-1]
                i-=1
            elif(mat[i-1][j]<mat[i][j-1]):
                ans+=b[j-1]
                j-=1
    
    while i>0:
        ans+=a[i-1]
        i-=1
    
    while j>0:
        ans+=b[j-1]
        j-=1
    
    return ans[::-1]

SCS(a,b,m,n)

'acbcdaf'

In [64]:
# Longest Repeated subSequence
import numpy as np

S="AABEBCDD"
a=S
b=S
m=len(S)
v=[-1]*((m+1)**2)

def LRS(a,b,m):
    mat=np.array(v).reshape(m+1,m+1)
    for i in range(m+1):
        for j in range(m+1):
            if(i==0 or j==0):
                mat[i][j]=0
    
    for i in range(1,m+1):
        for j in range(1,m+1):
            if(a[i-1]==b[j-1] and i!=j):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i-1][j],
                             mat[i][j-1])
    
    return mat[m][m]

LRS(a,b,m)

3

In [71]:
# Sequence Pattern Matching
import numpy as np

a="AXY"
b="ADXCPY"

m=len(a)
n=len(b)
v=[-1]*(m+1)*(n+1)

def SPM(a,b,m,n):
    mat=np.array(v).reshape(m+1,n+1)
    for i in range(m+1):
        for j in range(n+1):
            if i==0 or j==0:
                mat[i][j]=0
                
    for i in range(1,m+1):
        for j in range(1,n+1):
            if(a[i-1]==b[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i-1][j],
                             mat[i][j-1])
    if m==mat[m][n]:
        return True
    else:
        return False
    
SPM(a,b,m,n)

True

In [2]:
# Minimum no. of insertion in a String to make it a palindrome
import numpy as np

a="agbcba"
n=len(a)
b=a[::-1]
def min_insertion_to_make_pal(a,b,n):
    v=[-1]*((n+1)**2)
    mat=np.array(v).reshape(n+1,n+1)
    for i in range(n+1):
        for j in range(n+1):
            if i==0 or j==0:
                mat[i][j]=0
                
    for i in range(1,n+1):
        for j in range(1,n+1):
            if(a[i-1]==b[j-1]):
                mat[i][j]=1+mat[i-1][j-1]
            else:
                mat[i][j]=max(mat[i][j-1],
                             mat[i-1][j])
    return n-mat[n][n]

min_insertion_to_make_pal(a,b,n)

1

# Matrix Chain Multiplication

In [43]:
# Matrix Chain Multiplication (MCM)
# Recursive code

import sys
arr=[40,20,30,10,30]

def MCM(arr,i,j):
    if(i>=j):
        return 0
    mini=sys.maxsize
    for k in range(i,j):
        part=(MCM(arr,i,k)+MCM(arr,k+1,j))+(arr[i-1]*arr[k]*arr[j])
        if(part<mini):
            mini=part
        
    return mini

MCM(arr,1,len(arr)-1)
        

26000

In [25]:
# Matrix Chain Multiplication (Bottom up approach) (DP)

import numpy as np
import sys
arr=[40,20,30,10,30]
n=len(arr)
v=[-1]*((n+1)**2)

mat=np.array(v).reshape(n+1,n+1)

def MCM_DP(arr,i,j):
    if(i>=j):
        return 0
    if(mat[i][j]!=-1):
        return mat[i][j]
    mini=sys.maxsize
    for k in range(i,j):
        temp=MCM_DP(arr,i,k)+MCM_DP(arr,k+1,j)+(arr[i-1]*arr[j]*arr[k])
        
        if(temp<mini):
            mini=temp
    mat[i][j]=mini
    return mat[i][j]

MCM_DP(arr,1,len(arr)-1)
    

26000

In [23]:
# Palindrome Partation (minimum)
# Recursive 

import sys

s="anitin"
def ispal(s,i,j):
    s1=s[i:j]
    if(s1==s1[::-1]):
        return True
    else:
        return False

def PP(arr,i,j):
    if(i>=j):
        return 0
    if ispal(arr,i,j+1)==True:
        return 0
    
    mini=sys.maxsize
    for k in range(i,j):
        part=1+PP(arr,i,k)+PP(arr,k+1,j)
        if(part<mini):
            mini=part
    
    return mini

PP(s,0,len(s)-1)


1

In [7]:
# Palindrome Partation (Bottom up approach) (DP)

import numpy as np
import sys

s="nitik"
n=len(s)
v=[-1]*(n+1)*(n+1)

mat=np.array(v).reshape(n+1,n+1)

def isPal(s,i,j):
    s1=s[i:j]
    if(s1==s1[::-1]):
        return True
    else:
        return False
    
def PP_DP(arr,i,j):
    if(i>=j):
        return 0
    if(isPal(arr,i,j+1)):
        return 0
    if(mat[i][j]!=-1):
        return mat[i][j]
    mini=sys.maxsize
    for k in range(i,j):
        part=1+PP_DP(arr,i,k)+PP_DP(arr,k+1,j)
        if(part<mini):
            mini=part

    mat[i][j]=mini
    return mat[i][j]

PP_DP(s,0,len(s)-1)

2

In [69]:
# Evaluate Expression to True Boolean Parenthesization Recursive

s="T|T&F^T"

def solve(s,i,j,isTrue):
    if(i>j):
        return 0
    if(i==j):
        if(isTrue==1):
#             print(k)
            return 1 if s[i]=="T" else 0
        else:
            return 1 if s[i]=="F" else 0
    
    ans=0
    for k in range(i+1,j-1,2):
        lt=solve(s,i,k-1,1)
        print(lt)
        lf=solve(s,i,k-1,0)
#         print(lf)
        rt=solve(s,k+1,j,1)
#         print(rt)
        rf=solve(s,k+1,j,0)
#         print(rf)
        
        if(s[k]=="&"):
            if(isTrue==1):
                ans+ans+(lt*rt)
            else:
                ans=ans+(lt*rf)+(lf*rf)+(lf*rf)
            
#             print(ans)
        
        elif(s[k]=="|"):
            if(isTrue==1):
                ans=ans+(lt*rt)+(lf*rt)+(lt*rf)
            else:
                ans=ans+(lf*rf)
                
#             print(ans)
        
        elif(s[k]=="^"):
            if(isTrue==1):
#                 print(s[k])
                ans=ans+(lt*rf)+(lf*rt)
            else:
                ans=ans+(lt*rt)+(lf*rf)
            
#             print(ans)
    
    return ans

solve(s,0,len(s)-1,1)

# NOT COMPELTE

1
1
1
0


0

In [35]:
# Scramble String Recursive 

def Scramble(a,b):
    if(a==b):
        return True
    if(len(a)<=1):
        return False
    n=len(a)
    flag=False
    cond1=False
    cond2=False
    for i in range(1,n-1):
#         print(a[0:i])
#         print(b[n-i:i])
#         print(a[i:n-i])
#         print(b[0:n-i])
#         print("+++++++++++++++++++++")
        
        print(a[0:i])
        print(b[0:i])
        print(a[i:n-i])
        print(b[i:n-i])
        print("++++++++++++++++++++++")
        if((Scramble(a[0:i],b[n-i:i]))==True) and ((Scramble(a[i:n-i],b[0:n-i]))==True):
            cond1=True
            print(cond1)
        if((Scramble(a[0:i],b[0:i]))==True) and ((Scramble(a[i:n-i],b[i:n-i]))==True):
            cond2=True
            print(cond2)
        if(cond1 or cond2):
            flag=True
            break
    return flag
           

a="abc"
b="bac"
if(len(a)!=len(b)):
    print(False)
if(len(a)==0 and len(b)==0):
    print(True)
Scramble(a,b)

# NOT COMPLETE

a
b
b
a
++++++++++++++++++++++


False